### ISSUE TITLE
I get the "half" of the cells when exporting a MF6 model to VTK

### ISSUE THREAD

**Issue by sebmeng** [modflowpy/flopy#1372] opened 2022-03-11 14:36 UTC
Hello, community!
I created a MF6 model in GWV, and I was trying to see the results and the hydraulic conductivity distribution in 3D using floPy.  When I did this, I got the half of the cells (lower left triangle), instead of the whole cell (rectangles) as shown in the attached file:

![cells](https://user-images.githubusercontent.com/48210348/157887698-d135bb9c-bbe3-432f-9c9d-81f061536421.PNG)

For exporting the hydraulic properties stored in the NPF package, I used the following command:
gwf.npf.export(pv_folder, smooth=True, fmt='vtk', name='NPF', point_scalars=True)

I've also tried other ways to export the grid:
vtk.export_package( gwf ,pak_name='npf' ,otfolder=pv_folder,vtk_grid_type='UnstructuredGrid')

vtk.export_model( gwf , pv_folder,package_names='npf',point_scalars=True,vtk_grid_type='UnstructuredGrid')

But I get the same result.

am I missing something, or is there a bug unreported?
I'm using the 3.3.5 floPy version, and the 5.10.0 version of paraview.

thanks in advance for your valuable help!

Sebastian Mengual

**Comment by langevin-usgs** [comment] 2022-03-14 12:49
I'm sure this is something simple and possibly a bug in the flopy export.  Can you replicate the problem with a simple test model or upload your model files to this issue?  We can take a look.

**Comment by sebmeng** [comment] 2022-03-14 13:24
[model_MF6.zip](https://github.com/modflowpy/flopy/files/8245138/model_MF6.zip)

Thank you, Chris! I've attached the files,
I'm looking forward to your response,


Regards.

**Comment by sebmeng** [comment] 2022-03-14 17:37
> I'm sure this is something simple and possibly a bug in the flopy export. Can you replicate the problem with a simple test model or upload your model files to this issue? We can take a look.
[MF6.zip](https://github.com/modflowpy/flopy/files/8247250/MF6.zip)

Hello Chris! I am sending you again the files, the previous zip had some missing files.

 I'm looking forward to your response,


Regards.

**Comment by langevin-usgs** [comment] 2022-03-15 16:28
Hey @sebmeng, I had a chance to look into this yesterday and I think I know what the problem is. I just haven't had time to fix it.  I believe the issue is related to the list of vertices in the cell2d block of the DISU input file.  MODFLOW 6 will accept the list of vertices for each cell with the last vertex equal to the first vertex or without "closing" the cell polygon.  So for a square cell with 4 vertices, MODFLOW 6 will accept the following list of vertices [1, 2, 3, 4] or [1, 2, 3, 4, 1].  I think flopy is expecting the second version, where the first vertex must be repeated.  Your model does not repeat the first vertex.  Is there any way you can modify your disu input file in this manner and confirm this is the problem?  I suspect it will work.  I will try to confirm this is the issue and implement a fix sometime this week.

**Comment by jlarsen-usgs** [comment] 2022-03-19 00:20
@sebmeng 

I just submitted a pull request to fix this issue. The Vtk class was stripping off the first record in each set of vertices, because previously Stuctured and Vertex grid models supplied the cell number as the first record. This has been fixed, and now it is not necessary to have a closed polygon. 

In addition, I found and fixed a couple of other vtk export errors with regard to exporting UnstructuredGrid models.

**Closed** 2022-03-19 15:09 UTC
