### ISSUE TITLE
load file

### ISSUE THREAD

**Issue by sharon92** [modflowpy/flopy#593] opened 2019-06-12 15:22 UTC

**Comment by sharon92** [comment] 2019-06-12 15:29
Modflow can read global paths in .NAM file but not flopy.

Flopy tries to concatenate the given filename for a package with the Directory path of NAM File.

The code:
utils.mfreadnam.parsenamefile(namfilename, packages)
```
        # remove quotes in file path
        if '"' in fpath:
            fpath = fpath.replace('"', '')
        if "'" in fpath:
            fpath = fpath.replace("'", "")

        # need make filenames with paths system agnostic
        if '/' in fpath:
            raw = fpath.split('/')
        elif '\\' in fpath:
            raw = fpath.split('\\')
        else:
            raw = [fpath]
        fpath = os.path.join(*raw)

        fname = os.path.join(os.path.dirname(namfilename), fpath)
```
Maybe the right way would be to check if os.path.exists(fpath) first, and if not then do the concatenation.

It should also include directory walk options with "..\\"

**Comment by langevin-usgs** [comment] 2019-06-13 12:09
Do you know if this only occurs on Windows?  We should write a load test that reads a nam file that has absolute paths in it.  With os.path.abspath() we should be able to write a test that runs on Travis.

**Comment by sharon92** [comment] 2019-06-14 11:49
Sorry I only use windows for my work and don't know how Travis works...

Yes abspath seems like the right way. 
```
import os 

namfilename = r"z:\GWOW_Hanauerland\M06_MODFLOW\INSTAT\HLHW2013_K00\HLHW2013.nam"
fpath = r"z:\GWOW_Hanauerland\M06_MODFLOW\00_Modellaufbau\_LPF\HL130513.lpf"

if '"' in fpath:
    fpath = fpath.replace('"', '')
if "'" in fpath:
    fpath = fpath.replace("'", "")

abs_fpath = os.path.abspath(fpath)

if not os.path.isfile(abs_fpath) or not os.path.exists(abs_fpath):
    # need make filenames with paths system agnostic
    if '/' in fpath:
        raw = fpath.split('/')
    elif '\\' in fpath:
        raw = fpath.split('\\')
    else:
        raw = [fpath]
    fpath = os.path.join(*raw)
    
    fname = os.path.join(os.path.dirname(namfilename), fpath)

else:
    fname = fpath = abs_fpath
```

This returns the right fpath for the Modflow Package

**Comment by ougx** [comment] 2019-09-25 05:04
`fname = os.path.join(os.path.dirname(namfilename), fpath)` assumes that the working directory is the folder where the name file is located in, which is not always true.

`fpath` should be relative to the working directory:
`fname = os.path.join(os.path.dirname(model_ws), fpath)`

**Comment by jdhughes-usgs** [comment] 2020-06-25 18:58
duplicate of #633

**Comment by jdhughes-usgs** [comment] 2021-08-04 22:14
Reopen if this is still a valid issue.

**Closed by jdhughes-usgs** 2021-08-04 22:14 UTC
