### ISSUE TITLE
Model object does not have xcenters or ycenters attribute 

### ISSUE THREAD

**Issue by mrush-usgs** [modflowpy/flopy#1014] opened 2020-11-05 23:08 UTC
I am working on a plotting method that involves getting xcenters, ycenters, and zcenters. My model object does not have attributes xcenters or ycenters: 

flopy version: 3.3.2
Traceback (most recent call last):
line 140, in <module>
    frf, fff = vectorize_flow(ja, model.dis)
 line 46, in vectorize_flow
    xcenter = model.xcenters
  File "C:\ProgramData\Anaconda3\envs\mickey\lib\site-packages\flopy\mf6\mfmodel.py", line 218, in __getattr__
    raise AttributeError(item)
AttributeError: xcenters

But it looks like model.modelgrid has an xyzcellcenters attribute: 
    xyz = model.modelgrid.xyzcellcenters
    xcenter = xyz[0]
    ycenter = xyz[1]
    zcenter = xyz[2]

**Comment by emorway-usgs** [comment] 2020-11-06 17:04
Is this a question?  The end of your message suggests you found the solution?  In the future, you might consider posting questions on stackoverflow with a flopy tag.

**Comment by jlarsen-usgs** [comment] 2020-11-06 22:58
@emorway-usgs & @mrush-usgs,

I instructed mrush to open this issue as my understanding was that it was an issue with the plot_vectors() method on PlotMapView(). However, it seems like it is not. 

The flopy model object does not have a `xcenters` or 'ycenters` attribute. Instead the `model.modelgrid` (Grid object) has these attributes and is used for all plotting and exporting functions. 

I am closing this issue, because it seems like it is not a bug in the code.

**Closed** 2020-11-06 22:59 UTC
