### ISSUE TITLE
Mf6 disv error

### ISSUE THREAD

**Issue by MostafaGomaa93** [modflowpy/flopy#706] opened 2019-10-31 13:49 UTC
I am trying to build a modflow 6 model using disv package
I got this error and I don't understand why :
ERROR. VERTEX NUMBER NOT CONSECUTIVE.  LOOKING FOR 1 BUT FOUND 2

Another issue is that I have a cell2d text file (attached below) which should be ready to be read by the disv package, however, I don't why every time when the disv package read the cell2d file, it adds a number of  NonType objects to each cell list 
for ex:
in the text file: 
[1, 451.40725951649654, 408.73099226988086, 4, 4, 10, 2, 3]
[2, 2118.8043893585514, 4495.797899435779, 10, 51, 65, 45, 25, 26, 32, 33, 35, 36, 37]
[3, 3814.764860532474, 5333.728654312645, 7, 65, 51, 57, 68, 104, 109, 90]

but when the disv package read it, it becomes:
[1, 451.40725951649654, 408.73099226988086, 4, 4, 10, 2, 3, None, None, None, None, None,None]
[2, 2118.8043893585514, 4495.797899435779, 10, 51, 65, 45, 25, 26, 32, 33, 35, 36, 37]
[3, 3814.764860532474, 5333.728654312645, 7, 65, 51, 57, 68, 104, 109, 90, None, None,None,]

kindly I appreciate any help for fixing these errors
and also I would like to know for example which packages can be used to create a Voronoi grid in such a way to be ready for the disv such as the flopy.utils.triangle Module

Attached files are the cell2d.txt and the vertices.txt
[vor_cell2d.txt](https://github.com/modflowpy/flopy/files/3794607/vor_cell2d.txt)
[vor_vertices.txt](https://github.com/modflowpy/flopy/files/3794608/vor_vertices.txt)

**Comment by spaulins-usgs** [comment] 2019-10-31 15:58
It looks like the brackets [] in your vor_cell2d.txt and vor_vertices.txt files are confusing MODFLOW. Since Flopy is able to read these files I recommend reading in the files into a flopy disv object, something like this:

    disv = ModflowGwfdisv(model, ncpl=65, nlay=1, nvert=238, top=0.0,
                          botm=-100.0, idomain=1,
                          vertices={'filename': 'vor_vertices.txt'},
                          cell2d={'filename': 'vor_cell2d.txt'},
                          filename='test706_m.disv')

and then have flopy to write the data from those files out again:

    disv.vertices.set_data({'filename': 'vor_vertices_updated.txt', 'data': disv.vertices.get_data()})
    disv.cell2d.set_data({'filename': 'vor_cell2d_updated.txt', 'data': disv.cell2d.get_data()})
    sim.write_simulation()

This should remove the brackets from your data and allow MF6 to read it. 

None appears at the end of some of your data because your data is being stored in numpy recarrays. Numpy recarrays define specific data columns and can only represent jagged data like this by filling in the extra spaces with None. Flopy automatically ignores the Nones when it writes your data to a file.

Also, I noticed MODFLOW is giving another error "CELL2D AREA LESS THAN ZERO". It looks like the shapes of some of your cells may not be valid.

**Comment by MostafaGomaa93** [comment] 2019-11-01 09:07
thanks for the suggestions
I did them but still doesn't work. however, when I change the starting of the vertices list to 0 instead of 1, it works 
I just wonder why the model didn't accept it although it is mentioned in the disv description that the vertices list starts from 1 to NVRT

Another question please, now I got this error and I don't understand it 

forrtl: error (65): floating invalid
Image              PC                Routine            Line        Source             
mf6.exe            00007FF722BC9E07  DISVGEOM_mp_CPROP         165  DisvGeom.f90
mf6.exe            00007FF722BC5819  CONNECTIONSMODULE         943  Connections.f90
mf6.exe            00007FF722C06ED7  GWFDISVMODULE_mp_         809  gwf3disv8.f90
mf6.exe            00007FF722BFD62A  GWFDISVMODULE_mp_         129  gwf3disv8.f90
mf6.exe            00007FF722BD34B4  GWFMODULE_mp_GWF_         317  gwf3.f90
mf6.exe            00007FF722D0C412  MAIN__                     74  mf6.f90
mf6.exe            00007FF722E34B62  Unknown               Unknown  Unknown
mf6.exe            00007FF722E34F4C  Unknown               Unknown  Unknown
KERNEL32.DLL       00007FFFC4C47BD4  Unknown               Unknown  Unknown
ntdll.dll          00007FFFC4DCCED1  Unknown               Unknown  Unknown

**Comment by langevin-usgs** [comment] 2019-11-01 12:48
Without datafiles there is no way for us to determine the cause of the problem.  Vertices must be listed in clockwise order.  Cells must be convex.  Vertices along edges must be shared with adjacent cells so that connectivity can be determined.  This all needs to be done correctly or MODFLOW won't be able to run properly.  The problems you are having here are not a bug in Flopy so I'm closing this issue.

**Closed by langevin-usgs** 2019-11-01 12:48 UTC
