### ISSUE TITLE
Possible problems with Flopy processing Seawat outputs on Linux

### ISSUE THREAD

**Issue by FabioDioguardi** [modflowpy/flopy#1332] opened 2022-01-21 13:12 UTC
Dear all,

I am having problems when running the example in attachment in Linux environments using Flopy to post-process results. 
I have installed MODFLOW, SEAWAT and all the related software successfully, and the simulations run fine. However, when running this example on Linux (using both the official Flopy latest release and the one in the develop branch) I get the following error:

python example_2.py
3.8.12 | packaged by conda-forge | (default, Oct 12 2021, 21:57:06)
[GCC 9.4.0]
numpy version: 1.22.0
flopy version: 3.3.5
henry.nam

 Normal termination of SEAWAT
Note: The following floating-point exceptions are signalling: IEEE_DENORMAL
Traceback (most recent call last):
  File "example_2.py", line 99, in <module>
    ucnobj = bf.UcnFile(os.path.join(workspace, 'MT3D001.UCN'), model=swt)
  File "/home/fabiod/anaconda3/envs/hydro-jules_dev_original/lib/python3.8/site-packages/flopy/utils/binaryfile.py", line 559, in __init__
    super().__init__(filename, precision, verbose, kwargs)
  File "/home/fabiod/anaconda3/envs/hydro-jules_dev_original/lib/python3.8/site-packages/flopy/utils/binaryfile.py", line 280, in __init__
    super().__init__(filename, precision, verbose, kwargs)
  File "/home/fabiod/anaconda3/envs/hydro-jules_dev_original/lib/python3.8/site-packages/flopy/utils/datafile.py", line 200, in __init__
    self._build_index()
  File "/home/fabiod/anaconda3/envs/hydro-jules_dev_original/lib/python3.8/site-packages/flopy/utils/binaryfile.py", line 312, in _build_index
    header = self._get_header()
  File "/home/fabiod/anaconda3/envs/hydro-jules_dev_original/lib/python3.8/site-packages/flopy/utils/binaryfile.py", line 367, in _get_header
    return header[0]
IndexError: index 0 is out of bounds for axis 0 with size 0

Note that:
- I do not have any problem in plotting MODFLOW results. Furthermore, I do not have any problems on Windows.
- The problems happens also on other test cases, regardless the error message at the end of the Seawat run "Note: The following floating-point exceptions are signalling: IEEE_DENORMAL"

Could you please advise?
Thanks
Regards
Fabio

[example_2.txt](https://github.com/modflowpy/flopy/files/7913859/example_2.txt)

**Comment by langevin-usgs** [comment] 2022-01-21 13:55
Can you verify that the MT3D001.UCN file is present and is not empty?  Did you obtain the SEAWAT binary executable for linux from here (https://github.com/MODFLOW-USGS/executables)?

**Comment by FabioDioguardi** [comment] 2022-01-21 14:03
I can confirm the file is present and not empty. 
I am actually using a version of Seawat that I compiled (source code taken from here: [https://www.usgs.gov/software/seawat-computer-program-simulation-three-dimensional-variable-density-ground-water-flow]. Do you suggest using the binary executables instead? I was not aware they existed for linux.

Thanks
Fabio

**Comment by langevin-usgs** [comment] 2022-01-21 14:12
Yes, try that binary executable instead.  I think we modify the way the unformatted files are written.  Please close this comment if the problem is fixed.

**Closed** 2022-01-21 14:14 UTC

**Comment by langevin-usgs** [comment] 2022-01-21 14:17
No problem.  If you want to compile it yourself, you should use the pymake package (https://github.com/modflowpy/pymake).  We use pymake to help with the compilation and ensure that the executables work with flopy and our other tools.
