### ISSUE TITLE
gridgen module, function intersect: donuts in shape Modflow6

### ISSUE THREAD

**Issue by AvDKWR** [modflowpy/flopy#843] opened 2020-04-02 12:39 UTC
Hi,
Maybe this problem has already been discussed, I do not know, we just started with Modflow6 in Flopy.

We have a polygon shape file of locations with drainage. But this shapefile contains donuts, sometimes the donut has a value and sometimes the donut has no value (in GIS at this location there is no shape). 

When we use the command: gridgen module, function intersect.. we receive the rec.array with the intersection properties. But at locations of (1) a shapedonut with a value, we receive two properties (of the donut and the surrounding polygon and at (2) locations of a shapedonut with no value, we receive the value of the surrounding shapepolygon.

does anyone have an idea how the receive only the correct value?
-for donut with value: we only want to receive the value of the donut itself
-for donut without value: the function should not select this polygon.

would be great if there is a simple solution!
Annemieke

**Comment by langevin-usgs** [comment] 2020-04-02 13:10
While I believe that gridgen can process shapefiles with donuts, I'm not sure that the flopy gridgen module is set up to do so.  The flopy gridgen module is creating gridgen input files and running the gridgen program in the background.  You might look in these gridgen input and output modules to see if the information is correct in there.  Holes in shapes must be listed correctly (and with the correct vertex ordering) in a shapefile or gridgen won't be able to process them.  It is possible that you have a shapefile that will render in a gui, but will have incorrect topology.  Ultimately, your path of least resistance might be to create a shapefile without holes.

**Comment by AvDKWR** [comment] 2020-04-02 14:57
thanks for your reply! 

We use the same polygonenshape for several functions. For example the fucntion: add_refinement_features  to refine the grid, the same shape works fine. so we assumed it is a problem in the intersect comment. 

i understand we can change the shape, but since it is the source data (which is updated once a while), it would be much nicer if we can use it without adjustments or make automatic adjustments in python.

therefore i was just wondering if the problem has accured before..

**Comment by langevin-usgs** [comment] 2020-04-02 15:57
I see.  If there is any way you could create a simple and relatively small example that demonstrates the problem, then you could post the files here and I could take a look.  It might be something simple, and I agree that it would be nice if the intersect worked the same way as the other functions.  I'll close this issue for now, but if you do post an example, then we can reopen this issue.

**Comment by AvDKWR** [comment] 2020-04-03 08:37
thanks for your comment. I have uploaded a zip. it contains a notebook and two small shapefiles. You will need to adjust the path to the map with the shapefiles.

if you run the script you see, that the refinement is not done in the holes. But that the hole is incl
[river_intersect_issue.zip](https://github.com/modflowpy/flopy/files/4425892/river_intersect_issue.zip)
uded in the river package. If we show the shape intersect results (third picture) you see that the river "sees" two polygons at these locations.

**Comment by AvDKWR** [comment] 2020-04-03 08:40
Hi, I have uploaded a small example in the closed topic. I am only not sure if this still works since it is closed.

TEXT

thanks for your comment. I have uploaded a zip. it contains a notebook and two small shapefiles. You will need to adjust the path to the map with the shapefiles.

if you run the script you see, that the refinement is not done in the holes. But that the hole is included in the river package. If we show the shape intersect results (third picture) you see that the river "sees" two polygons at these locations.

Kind regards,

Annemieke

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Comment by langevin-usgs** [comment] 2020-04-06 13:54
I verified that something seems wrong here, but after a quick look, I couldn't tell if the problem is in gridgen, the shapefiles, or the gridgen flopy wrapper.  Reopening...

**Comment by dbrakenhoff** [comment] 2020-04-06 14:19
For what it's worth, the shapefiles work fine when intersecting with a regular grid using GridIntersect... 
I was curious, so I tried that out.

**Comment by langevin-usgs** [comment] 2020-04-06 14:26
Thanks, @dbrakenhoff.  I like the idea of just using GridIntersect for this.  The challenge here is that someone would need to convert their shapefile into something that GridIntersect can process (including making sure holes are represented correctly).  Is there a simple way to do this, or would someone need to read through the shapefile processing each polygon one by one?

**Comment by dbrakenhoff** [comment] 2020-04-06 14:48
You need to get the shapes as Shapely geometries. I just used geopandas to load the shapefile. That is probably the easiest method. Otherwise fiona/shapely could be used I think (which is what geopandas does behind the scenes). 
I'm not sure which dependencies flopy is using for shapefiles at the moment? If it's pyshp, the __geo_interface__ attribute can probably be used to convert to shapely.

My attempt is in the attached notebook. What I couldn't figure out is how to get a modelgrid object that describes the locally refined grid from the gridgen object. 

[grid_intersect_shp_with_holes.zip](https://github.com/modflowpy/flopy/files/4439060/grid_intersect_shp_with_holes.zip)

**Comment by langevin-usgs** [comment] 2020-04-06 15:19
Hey @dbrakenhoff, I can get it close with this:

```
sim = flopy.mf6.MFSimulation()
gwf = flopy.mf6.ModflowGwf(sim)
gridprops_disv = g.get_gridprops_disv()
disv = flopy.mf6.ModflowGwfdisv(gwf, **gridprops_disv)
modelgrid_qt = gwf.modelgrid

ix = flopy.utils.GridIntersect(modelgrid_qt)
res = ix.intersect_polygon(shp)
```

but then it fails with this:

![image](https://user-images.githubusercontent.com/3372403/78574700-ffc1c700-77ef-11ea-9395-636aa7739575.png)

Any ideas?  I think we're close.

**Comment by dbrakenhoff** [comment] 2020-04-06 15:33
The gridcell it's trying to intersect isn't valid. It's sort of a line...

![image](https://user-images.githubusercontent.com/6552225/78576124-8b594900-782c-11ea-8b7e-15df3d7b9b9a.png)

**Comment by dbrakenhoff** [comment] 2020-04-06 15:45
I'm guessing I didn't implement the cell2d to polygon conversion correctly for locally refined grids in `_vtx_grid_to_shape_list`. There's a bunch of these invalid gridcells in there. Maybe because I focused on a triangular mesh when writing this vertex grid code...

I only use ivert 0 to 2 ...
```python
for iv in self.mfgrid._cell2d[["icvert_0", "icvert_1", "icvert_2"]][icell]:
    points.append((self.mfgrid._vertices.xv[iv], self.mfgrid._vertices.yv[iv]))
```
I can fix that if you want, unless you already have a solution?

**Comment by langevin-usgs** [comment] 2020-04-06 15:52
That looks like a bug in the gridgen wrapper. These points should define a valid cell.  Let me look.

**Comment by langevin-usgs** [comment] 2020-04-06 16:01
I see now.  Yes, we need to use all the vertices to create the cell.  @dbrakenhoff, would you mind submitting a fix for this?

**Comment by dbrakenhoff** [comment] 2020-04-06 16:07
I think I've fixed it. I'll submit a fix. This is the result when I use all the vertices:

![image](https://user-images.githubusercontent.com/6552225/78579547-65827300-7831-11ea-8344-590c107fccea.png)

**Comment by langevin-usgs** [comment] 2020-04-06 16:23
Awesome!  Thank you.

**Comment by AvDKWR** [comment] 2020-04-06 18:42
I think you fixed it? wow that is very great, thank you so much :)

**Comment by langevin-usgs** [comment] 2020-04-06 18:45
Well, not exactly.  @dbrakenhoff fixed the flopy intersect capabilities so that they work with the gridgen module, so you will have to use those instead of the intersect that comes with gridgen.  So we should leave this issue open.  Hopefully you can figure out how to adapt your script using the few pieces of code that we added above.

**Comment by AvDKWR** [comment] 2020-04-13 13:53
Thanks a lot for your help the past week!! It is working fine now with your suggestions, and our modelscript is running :)

**Closed** 2020-06-09 17:47 UTC
