### ISSUE TITLE
Issue with  sim.simulation_data.mfdata()

### ISSUE THREAD

**Issue by giovannifi** [modflowpy/flopy#822] opened 2020-03-04 08:01 UTC
I slightly modified the code available here:

https://github.com/modflowpy/flopy/blob/develop/examples/Notebooks/flopy3_mf6_tutorial.ipynb

I have just added at the end of the code the following line:

`flux = sim.simulation_data.mfdata['example_model', 'CBC', 'WEL']`

When I run the script I get the following error:

`Traceback (most recent call last):
  File "H:/scripts/python3.6/testing/testing_cbb.py", line 157, in <module>
    flux = sim.simulation_data.mfdata['example_model', 'CBC', 'WEL']
  File "C:\Program Files\Python36\lib\site-packages\flopy\mf6\modflow\mfsimulation.py", line 79, in __getitem__
    val = binaryfile_utils.MFOutput(self, self._path, key)
  File "C:\Program Files\Python36\lib\site-packages\flopy\mf6\utils\binaryfile_utils.py", line 35, in __init__
    data = MFOutputRequester(mfdict, path, key)
  File "C:\Program Files\Python36\lib\site-packages\flopy\mf6\utils\binaryfile_utils.py", line 88, in __init__
    self.querybinarydata = self._querybinarydata(key)
  File "C:\Program Files\Python36\lib\site-packages\flopy\mf6\utils\binaryfile_utils.py", line 106, in _querybinarydata
    return np.array(bindata.get_data(text=key[-1], full3D=True))
  File "C:\Program Files\Python36\lib\site-packages\flopy\utils\binaryfile.py", line 1147, in get_data
    rec = self.get_record(idx, full3D=full3D)
  File "C:\Program Files\Python36\lib\site-packages\flopy\utils\binaryfile.py", line 1433, in get_record
    raise ValueError(s)
ValueError: Returning WEL as `

Without having success with that command I tried another way:

`import flopy.utils.binaryfile as bf`
`cbb = bf.CellBudgetFile(sim_path + '\\' + 'example_model.cbc')`

In this case I get the following error:

`Traceback (most recent call last):
  File "H:/scripts/python3.6/testing/testing_cbb.py", line 158, in <module>
    cbb = bf.CellBudgetFile(sim_path + '\\' + 'example_model.cbc')
  File "C:\Program Files\Python36\lib\site-packages\flopy\utils\binaryfile.py", line 631, in __init__
    self._build_index()
  File "C:\Program Files\Python36\lib\site-packages\flopy\utils\binaryfile.py", line 727, in _build_index
    self._skip_record(header)
  File "C:\Program Files\Python36\lib\site-packages\flopy\utils\binaryfile.py", line 785, in _skip_record
    raise Exception('invalid method code ' + str(imeth))
Exception: invalid method code 1396179567`

Any help will be appreciated.

Many thanks in advance
PS. below you can find the entire script I am running

`import os
import sys
from shutil import copyfile
import flopy.utils.binaryfile as bf

import numpy as np
import matplotlib as mpl
import matplotlib.pyplot as plt

try:
    import flopy
except:
    fpth = os.path.abspath(os.path.join('..', '..'))
    sys.path.append(fpth)
    import flopy

path_exe = r'C:\Windows\ccmcache\MODFLOW\mf6.1.0\bin\mf6.exe'
print(sys.version)
print('numpy version: {}'.format(np.__version__))
print('matplotlib version: {}'.format(mpl.__version__))
print('flopy version: {}'.format(flopy.__version__))

sim_name = 'example_sim'
sim_path = r'C:\Working_Folder\test_models\test_inj_opt_mf6_v5'
sim = flopy.mf6.MFSimulation(sim_name=sim_name, version='mf6', exe_name=path_exe,
                             sim_ws=sim_path)

tdis = flopy.mf6.ModflowTdis(sim, pname='tdis', time_units='DAYS', nper=2,
                             perioddata=[(1.0, 1, 1.0), (10.0, 5, 1.0)])

model_name = 'example_model'
model = flopy.mf6.ModflowGwf(sim, modelname=model_name,
                             model_nam_file='{}.nam'.format(model_name))

ims_package = flopy.mf6.ModflowIms(sim, pname='ims', print_option='ALL',
                                   complexity='SIMPLE', outer_hclose=0.00001,
                                   outer_maximum=50, under_relaxation='NONE',
                                   inner_maximum=30, inner_hclose=0.00001,
                                   linear_acceleration='CG',
                                   preconditioner_levels=7,
                                   preconditioner_drop_tolerance=0.01,
                                   number_orthogonalizations=2)

sim.register_ims_package(ims_package, [model_name])
dis_package = flopy.mf6.ModflowGwfdis(model, pname='dis', length_units='FEET', nlay=2,
                                      nrow=2, ncol=5, delr=500.0,
                                      delc=500.0,
                                      top=100.0, botm=[50.0, 20.0],
                                      filename='{}.dis'.format(model_name))

# set the nocheck property in the simulation namefile
sim.name_file.nocheck = True
# set the print_input option in the model namefile
model.name_file.print_input = True

# Turn Newton option on with under relaxation
model.name_file.newtonoptions = ('UNDER_RELAXATION')
# Turn Newton option on without under relaxation
model.name_file.newtonoptions = ('')
# Turn off Newton option
model.name_file.newtonoptions = (None)
# build a data template for k that stores the first layer as an internal array and the second
# layer as a constant with the default value of k for all layers set to 100.0
layer_storage_types = [flopy.mf6.data.mfdatastorage.DataStorageType.internal_array,
                       flopy.mf6.data.mfdatastorage.DataStorageType.internal_constant]
k_template = flopy.mf6.ModflowGwfnpf.k.empty(model, True, layer_storage_types, 100.0)
# change the value of the second layer to 50.0
k_template[0]['data'] = [65.0, 60.0, 55.0, 50.0, 45.0, 40.0, 35.0, 30.0, 25.0, 20.0]
k_template[0]['factor'] = 1.5
print(k_template)
# create npf package using the k template to define k
npf_package = flopy.mf6.ModflowGwfnpf(model, pname='npf', save_flows=True, icelltype=1, k=k_template)
strt={'filename': 'strt.txt', 'factor':1.0, 'data':[100.0, 100.0, 100.0, 100.0, 100.0, 100.0, 100.0, 100.0, 100.0, 100.0,
      90.0, 90.0, 90.0, 90.0, 90.0, 90.0, 90.0, 90.0, 90.0, 90.0], 'binary': 'True'}
ic_package = flopy.mf6.ModflowGwfic(model, pname='ic', strt=strt,
                                    filename='{}.ic'.format(model_name))

# create storage package
sto_package = flopy.mf6.ModflowGwfsto(model, pname='sto', save_flows=True, iconvert={'filename':'iconvert.txt'},
                                      ss=[0.000001, 0.000002],
                                      sy=[0.15, 0.14, 0.13, 0.12, 0.11, 0.11, 0.12, 0.13, 0.14, 0.15,
                                         0.15, 0.14, 0.13, 0.12, 0.11, 0.11, 0.12, 0.13, 0.14, 0.15])
maxbound = 2
# build a stress_period_data template with 2 wells over stress periods 1 and 2 with boundnames
# and three aux variables
wel_periodrec = flopy.mf6.ModflowGwfwel.stress_period_data.empty(model, maxbound=maxbound, boundnames=True,
                                                             aux_vars=['var1', 'var2', 'var3'],
                                                             stress_periods=[0,1])
# define the two wells for stress period one
wel_periodrec[0][0] = ((0,1,2), -50.0, -1, -2, -3, 'First Well')
wel_periodrec[0][1] = ((1,1,4), -25.0, 2, 3, 4, 'Second Well')
# define the two wells for stress period two
wel_periodrec[1][0] = ((0,1,2), -200.0, -1, -2, -3, 'First Well')
wel_periodrec[1][1] = ((1,1,4), -4000.0, 2, 3, 4, 'Second Well')
# build the well package
wel_package = flopy.mf6.ModflowGwfwel(model, pname='wel', print_input=True, print_flows=True,
                                      auxiliary=['var1', 'var2', 'var3'], maxbound=maxbound,
                                      stress_period_data=wel_periodrec, boundnames=True, save_flows=True)
# printrecord data as a list of tuples.  since no stress
# period is specified it will default to stress period 1
printrec_tuple_list = [('HEAD', 'ALL'), ('BUDGET', 'ALL')]
# saverecord data as a dictionary of lists of tuples for
# stress periods 1 and 2.
saverec_dict = {0:[('HEAD', 'ALL'), ('BUDGET', 'ALL')],1:[('HEAD', 'ALL'), ('BUDGET', 'ALL')]}
# create oc package
oc_package = flopy.mf6.ModflowGwfoc(model, pname='oc',
                                    budget_filerecord=[('{}.cbc'.format(model_name),)],
                                    head_filerecord=[('{}.hds'.format(model_name),)],
                                    saverecord=saverec_dict,
                                    printrecord=printrec_tuple_list)
# add stress period two to the print record
oc_package.printrecord.add_transient_key(1)
# set the data for stress period two in the print record
oc_package.printrecord.set_data([('HEAD', 'ALL'), ('BUDGET', 'ALL')], 1)
rch_recarray = {0:[((0,0,0), 'rch_1'), ((1,1,1), 'rch_2')],
                1:[((0,0,0), 'rch_1'), ((1,1,1), 'rch_2')]}
rch_package = flopy.mf6.ModflowGwfrch(model, pname='rch', fixed_cell=True, print_input=True,
                                      maxbound=2, stress_period_data=rch_recarray)
# build a time series array for the recharge package
ts_data = [(0.0, 0.015, 0.0017), (1.0, 0.016, 0.0019), (2.0, 0.012, 0.0015),
           (3.0, 0.020, 0.0014), (4.0, 0.015, 0.0021), (5.0, 0.013, 0.0012),
           (6.0, 0.022, 0.0012), (7.0, 0.016, 0.0014), (8.0, 0.013, 0.0011),
           (9.0, 0.021, 0.0011), (10.0, 0.017, 0.0016), (11.0, 0.012, 0.0015)]
rch_package.ts.initialize(time_series_namerecord=['rch_1', 'rch_2'],
                          timeseries=ts_data, filename='recharge_rates.ts',
                          interpolation_methodrecord=['stepwise', 'stepwise'])

# build an recharge observation package that outputs the western recharge to a binary file and the eastern
# recharge to a text file
obs_data = {('rch_west.csv', 'binary'): [('rch_1_1_1', 'RCH', (0, 0, 0)),
                                    ('rch_1_2_1', 'RCH', (0, 1, 0))],
             'rch_east.csv': [('rch_1_1_5', 'RCH', (0, 0, 4)),
                              ('rch_1_2_5', 'RCH', (0, 1, 4))]}
rch_package.obs.initialize(filename='example_model.rch.obs', digits=10,
                           print_input=True, continuous=obs_data)
# write simulation to new location
sim.write_simulation()

# run simulation
sim.run_simulation()

keys = sim.simulation_data.mfdata.output_keys()
import matplotlib.pyplot as plt
import numpy as np

# get all head data
head = sim.simulation_data.mfdata['example_model', 'HDS', 'HEAD']
# get the head data from the end of the model run
head_end = head[-1]
# plot the head data from the end of the model run
levels = np.arange(160,162,1)
extent = (0.0, 1000.0, 2500.0, 0.0)
plt.contour(head_end[0, :, :],extent=extent)
plt.show()

# flux = sim.simulation_data.mfdata['example_model', 'CBC', 'WEL']
cbb = bf.CellBudgetFile(sim_path + '\\' + 'example_model.cbc')`

**Comment by spaulins-usgs** [comment] 2020-03-04 15:32
@giovannifi The budget file is being stored as double precision.  Try the following...

import flopy.utils.binaryfile as bf
cbb = bf.CellBudgetFile(sim_path + '\\' + 'example_model.cbc', precision='double')
data = np.array(cbb.get_data(text='WEL', full3D=False))

I have confirmed that flopy is not working correctly when executing:

flux = sim.simulation_data.mfdata['example_model', 'CBC', 'WEL']

The problem is that binaryfile_utils always tries to open the budget file with full3D set to True.  The WEL data is being stored using imeth=6, which does not allow full3D.  @jlarsen-usgs can you fix binaryfile_utils.py this so that the full3D option is only set in the appropriate cases?

**Comment by giovannifi** [comment] 2020-03-05 02:56
Thanks a lot for your prompt reply with this. The precision option for the
traditional method to read the budget file worked fine. The command
np.array(cbb.get_data(text='WEL', full3D=False)) worked also without the
full3D option. Even though I can get the full time series from get_data and
I am happy with that, I tried to use the get_ts as follows:

flux = cbb.get_ts(idx=(0,1,2), text='WEL')

but this returned the following error message:

Traceback (most recent call last):
  File "H:/scripts/python3.6/testing/testing_cbb.py", line 159, in <module>
    flux = cbb.get_ts(idx=(0,1,2), text='WEL')
  File "C:\Program
Files\Python36\lib\site-packages\flopy\utils\binaryfile.py", line 1217, in
get_ts
    v = self.get_data(kstpkper=k, text=text, full3D=True)
  File "C:\Program
Files\Python36\lib\site-packages\flopy\utils\binaryfile.py", line 1147, in
get_data
    rec = self.get_record(idx, *full3D=full3D*)
  File "C:\Program
Files\Python36\lib\site-packages\flopy\utils\binaryfile.py", line 1433, in
get_record
    raise ValueError(s)
ValueError: Returning WEL as

I tried then to run the command:

flux = cbb.get_ts(idx=(0,1,2), text='WEL', full3D=False)

that returned:

Traceback (most recent call last):
  File "H:/scripts/python3.6/testing/testing_cbb.py", line 159, in <module>
    flux = cbb.get_ts(idx=(0,1,2), text='WEL', full3D=False)
TypeError: get_ts() got an unexpected keyword argument 'full3D'

I suspect that there is a problem with the full3D option even in this case.

Kind Regards

**Comment by jlarsen-usgs** [comment] 2020-03-05 17:53
@giovannifi 

thanks for pointing out that the `get_ts()` method also does not work with data stored using IMETH=6. I'm currently working on a fix for the issue and will be submitting a PR soon.

**Comment by jlarsen-usgs** [comment] 2020-04-10 18:18
@giovannifi 

Pull request fixing this issue was merged into develop.

**Closed by jlarsen-usgs** 2020-04-10 18:18 UTC
