### ISSUE TITLE
bug: incorrect "WARNING: Unable to resolve dimension" in timeseries package

### ISSUE THREAD

**Issue by mbakker7** [modflowpy/flopy#1584] opened 2022-10-13 14:03 UTC
The timeseries package gives a warning for all the timeseries examples in the docs:
`WARNING: Unable to resolve dimension of ('ts', 'timeseries', 'timeseries', 'ts_array') based on shape "time_series_names"`

See https://flopy.readthedocs.io/en/latest/_notebooks/tutorial03_mf6_data.html

I don't understand why this warning is thrown, as the code runs fine. So why the warning?
If the warning is important, maybe show in the docs why it is important to change the code so that the warning disappears, and show how the warning can be avoided.

**Comment by langevin-usgs** [comment] 2022-10-13 14:07
I agree.  @spaulins-usgs, can you find a way to eliminate this warning or only warn when there is a problem?

**Comment by spaulins-usgs** [comment] 2022-10-13 21:59
@mbakker7, @langevin-usgs, in the tutorial a timeseries package is being constructed since the general head boundary package object is being constructed with the timeseries=ts_data parameter included.  Since the time series package is initially being constructed without a time series name record (it is initialized later in this example), the time series data dimensions can not be resolved and flopy is forced to accept the data without checking that the dimensions are correct.  Flopy therefore gives a warning letting the user know that it is unable to resolve the dimensions of the time series data and therefore cannot verify that the dimensions are correct.

The options I see are to:
1) Only display this warning in verbose mode
2) Only display all flopy warnings in verbose mode
3) Remove this warning as unnecessary
4) Leave the warning as is

Also, since it appears this warning is not clear, assuming we keep the warning I will change it to include the text, "unable to verify that ts_array has the correct dimensions".

Note that there is a bug being displayed in the tutorial.  Later in the tutorial flopy is unable to resolve the dimensions of sfacrecord.  I just verified that this is because the shape of sfacrecord is defined incorrectly in the dfn file.  I will fix the dfn file when I update flopy with the option above we agree upon.

**Comment by mbakker7** [comment] 2022-10-14 07:31
@spaulins-usgs, thanks for looking into this. 
I am a bit confused about how this works and where it can go wrong. 
For example, in the first example in the docs, first `ts_data` is built. This `ts_data` is then given to the `ghb` constructor using the `timeseries` keyword. That is when the warnings occurs.

Questions:
1. Why can flopy not check at time of the ghb construction whether this time series meets the requirements? 
2. Does flopy check anywhere else whether the time series meets the conditions?

In the docs, there is a second approach to add a time series, but the same warning is shown. To me it appears that the warning is always thrown, no matter how you construct the time series, and there is no way to add a time series that avoids this warning (at least not in the docs). Am I correct, or am I missing someting?

**Comment by spaulins-usgs** [comment] 2022-10-14 15:34
@mbakker7,

1. The time series (ts_data) dimensions are dependent on the number of items in the time series name record (time_series_namerecord).  For example, if time_series_namerecord was simply:

    time_series_namerecord="tides"

flopy would expect the time series data to contain two columns, a time column and a column for the value of "tides".  However, if the time_series_namerecord had two names:

    time_series_namerecord=[("tides", "other")]

flopy would expect the time series data to contain three columns, a time column, a column for the value of "tides", and a column for the value of "other".  

In the docs first example the ts_data is passed to flopy before time_series_namerecord, so flopy can not determine the correct dimensions of ts_data at the time it is passed to flopy.  For flopy to determine (and check) the correct dimensions of ts_data, you must pass both time_series_namerecord and ts_data at the same time, which can be done using .initialize.  For example:

    ghb = flopy.mf6.modflow.mfgwfghb.ModflowGwfghb(
        gwf,
        print_input=True,
        print_flows=True,
        save_flows=True,
        boundnames=True,
        pname="ghb",
        maxbound=30,
        stress_period_data=ghb_spd_ts,
    )
    
    ghb.ts.initialize(
        filename="tides.ts",
        timeseries=ts_data,
        time_series_namerecord="tides",
        interpolation_methodrecord="linearend",
        sfacrecord=1.1,
    )

2. Whenever possible flopy does check to make sure your time series is the proper dimensions.  If you change time_series_namerecord in the above example to :

        time_series_namerecord=[("tides", "other")],

and try to run it with the original ts_data with just two columns, flopy will produce an error, "Data line (0.0, 0.0) only has 2 entries, minimum number of entries is 3.".

Regarding the second example in the docs, where flopy is unable to resolve the dimensions of sfacrecord, this is a bug which is currently being fixed.  See the last paragraph of my response yesterday (above) for more details on that bug.

**Comment by mbakker7** [comment] 2022-10-17 07:51
Thanks for the clear explanation @spaulins-usgs. 
As you explain, when a time series is passed directly to a package, it can not be determined whether the time series has the right number of columns, because the `time_series_namerecord` is not passed to the package. This `time_series_namerecord` and other time series features must be set separately, using an `initialize` function. To be honest, that kind of goes against the design of flopy: all information can be passed to a package with (keyword)arguments. Right now, a time series can not be passed to a package without resulting in a warning and without needing an additional  `initialize` step. The initialization is a step that flopy is easily able to do on its own so we should design flopy so that the user is not burdened by this additional step.

A solution that I want to propose is that each package that can accept a time series as input, also has a keyword argument to pass all time series related information. For example, a dictionary `timeseries_settings`, where all additional settings are passed, such as `time_series_namerecord`, `interpolation_methodrecord`, etc. Then the package can do the initialization, check the dimensions of the time series and throw a warning when they don't match.

Thoughts?

**Comment by spaulins-usgs** [comment] 2022-10-17 22:01
@mbakker7, sorry when I wrote, "you must pass both time_series_namerecord and ts_data at the same time, which can be done using .initialize", I did not mean to imply that .initialize is the only way to pass all the timeseries data at once.  The timeseries parameter also accepts a dictionary.  This is the dictionary you are describing in your proposed solution.  So you can already do something like this:

    ts_dict = {"filename": "tides.ts",
               "timeseries": ts_data,
               "time_series_namerecord": "tides",
               "interpolation_methodrecord": "linearend",
               "sfacrecord": 1.1}

    # build ghb package
    ghb = flopy.mf6.modflow.mfgwfghb.ModflowGwfghb(
        gwf,
        pname="ghb",
        maxbound=30,
        timeseries=ts_dict,
        stress_period_data=ghb_spd_ts,
    ) 

I think this is similar to your proposed solution.  The only difference is the parameter name ("timeseries" instead of "timeseries_settings").  The "timeseries" attribute accepting a dictionary is documented here:

https://flopy.readthedocs.io/en/latest/source/flopy.mf6.modflow.mfgwfghb.html

Given that most people seem to favor the tutorials over the flopy source code docs, here is what I have on my todo list:
1) Add an example to the tutorial notebooks showing how to specify "timeseries" as a dictionary
2) Fix the sfacrecord bug

If I am missing anything let me know.

**Comment by spaulins-usgs** [comment] 2022-10-21 19:43
Just merged a PR into the develop branch that has an example of how to specify timeseries as a dictionary and has a fix for the sfacrecord bug.

**Closed by spaulins-usgs** 2022-10-21 19:43 UTC
Labels: bug

**Comment by martinvonk** [comment] 2023-09-10 13:08
I'm running into the same issue as @mbakker7 when using the RCH package. I've used both methods: 1. _initialize_ and 2. _timeseries dict_ but I'm getting the same warning message: `WARNING: Unable to resolve dimension of ('ts', 'attributes', 'sfacrecord_single', 'sfacval') based on shape "time_series_name".` Looking at the MF6 Tutorial Notebook on the Time Series Package the warning is raised there as well for both methods: [https://flopy.readthedocs.io/en/3.4.2/Notebooks/mf6_data_tutorial03.html](https://flopy.readthedocs.io/en/3.4.2/Notebooks/mf6_data_tutorial03.html)

Am I still doing something wrong since I'm still getting the warning? @spaulins-usgs 

Code to reproduce the error:

**General Code**
```python
import flopy
import numpy as np
r = np.array([0, 1e-3, 3e-3, 0])
nper = len(r)
rts = [(i, x) for i, x in zip(range(nper + 1), np.append(r, 0.0))]

sim = flopy.mf6.MFSimulation()

_ = flopy.mf6.ModflowTdis(sim, nper=nper, perioddata=[(1, 1, 1) for _ in range(nper)])

gwf = flopy.mf6.ModflowGwf(sim)
```
**Initialize method**
```python
rch = flopy.mf6.ModflowGwfrch(
    gwf,
    maxbound=1,
    pname="rch",
    stress_period_data={0: [[(0, 0, 0), "recharge"]]},
)
rch.ts.initialize(
    filename="recharge.ts",
    timeseries=rts,
    time_series_namerecord="recharge",
    interpolation_methodrecord="stepwise",
    sfacrecord=1.1,
    pname="rchts",
)
```

**Time Series Dictionary method**
```python
ts_dict = {
    "filename": "recharge.ts",
    "timeseries": rts,
    "time_series_namerecord": "recharge",
    "interpolation_methodrecord": "stepwise",
    "sfacrecord": 1.1,
}
 rch = flopy.mf6.ModflowGwfrch(
    gwf,
    maxbound=1,
    pname="rch",
    stress_period_data={0: [[(0, 0, 0), "recharge"]]},
    timeseries=ts_dict,
)
```

**Comment by martinvonk** [comment] 2023-09-10 15:33
Removing the `sfacrecord: 1.1` entry resolved the issue for me.
