### ISSUE TITLE
Cant load a USG recharge file because line 396 of mfrch.py wants nrow and ncol

### ISSUE THREAD

**Issue by laat0003** [modflowpy/flopy#633] opened 2019-08-22 01:14 UTC

**Comment by laat0003** [comment] 2019-08-22 01:34
The Util2d.load at line 396 in mfrch.py currently (v:3.2.12) is requesting nrow and ncol. I am trying to load a USG model with DISU, which loads fine (as do all the other packages) but it can't load the RCH and EVT packages because I get this error:

TypeError: unsupported operand type(s) for *: 'NoneType' and 'int'

I tried replacing the (nrow, ncol) with shape just for luck but I'm not Irish :)

If you could please suggest a workaround that would be great because I am trying to show off some flopy skills at my new job and everything model in USG.

I'd upload the recharge file but it's too large so I'll just give you the top part
# MODFLOW-USGs Recharge Package
 3 50
 1
INTERNAL  1.000000e+000  (FREE)  -1  RECHARGE
 1.000000e-007...(continues for number of nodes)

**Comment by langevin-usgs** [comment] 2019-08-22 13:41
I believe the way this is supposed to work is that nrow should be None for an unstructured disu model and ncol is basically the nodelay array.  And util2d should do things differently if nrow is None.  For example, the code below is used to return an array from util2d.

```
    def array(self):
        '''
        Return a numpy array of the 3D shape.  If an unstructured model, then
        return an array of size nodes.

        '''
        nlay, nrow, ncol = self.shape
        if nrow is not None:
            # typical 3D case
            a = np.empty((self.shape), dtype=self._dtype)
            # for i,u2d in self.uds:
            for i, u2d in enumerate(self.util_2ds):
                a[i] = u2d.array
        else:
            # unstructured case
            nodes = ncol.sum()
            a = np.empty((nodes), dtype=self._dtype)
            istart = 0
            for i, u2d in enumerate(self.util_2ds):
                istop = istart + ncol[i]
                a[istart:istop] = u2d.array
                istart = istop
        return a
```

I can't reproduce your problem, so it is tricky for me to do anything about this quickly.  It would be very helpful if you create a small disu model that shows the problem.  Recharge is tricky with the way it is handled in USG, but we should be able to get FloPy to support it.

**Comment by laat0003** [comment] 2019-08-23 05:52
Cheers for the rapid response. I very much appreciate it. I'll create a model over the weekend. I'm still new at the office so can't spend too much time on a side hustle. :)

I did track the error down in more detail, though.

"nrow" is getting read as None and "ncol" is being read correctly as the "nodelay" array. It looks like Util2d.load_txt() is where it all comes unstuck.

The control record dictionary ("cr_dict") type is "internal" for my recharge file (see line 2692 util_array.py).

The next line (2693 util_array.py) creates the "data" input for u2d by calling Util2d.load_txt()

The variable "shape" is a tuple of (nrow, ncol), which for USG is (None,[nodelay]) as you've stated. If len(shape) == 2 then Util2d.load_txt() attempts to multiply "nrow" by "ncol" (line 2375 util_array.py) resulting in the error: 

TypeError: unsupported operand type(s) for *: 'NoneType' and 'int'

**Comment by jdhughes-usgs** [comment] 2020-06-09 16:39
@langevin-usgs can we close this?

**Comment by langevin-usgs** [comment] 2020-06-09 17:53
I believe this is a duplicate of https://github.com/modflowpy/flopy/issues/896

**Closed** 2021-07-13 22:18 UTC
