### ISSUE TITLE
laytyp is returned as "NoneType" in MP7.py for structured grids in 3.2.12

### ISSUE THREAD

**Issue by TroelsNV** [modflowpy/flopy#692] opened 2019-10-23 19:33 UTC
MP7.py:
Line 331: return np.array(laytyp, dtype=np.int32)

Issue:
The laytyp returns NoneType since the laytyp is assigned to the package object and not the base modflow object.

e.g. "upw.laytyp" returns a Util2D array, but mf.laytyp returns None (here upw is the name of a ModflowUPW object and mf is a Modflow object)

**Comment by jlarsen-usgs** [comment] 2019-10-28 19:28
@TroelsNV, I'll take a look at this issue this afternoon.

**Comment by jlarsen-usgs** [comment] 2019-10-28 19:39
@TroelsNV, can you supply more information or your script that you are working with. I'm unable to reproduce this error with my simple test case.

The `BaseModel` class (base for `Modflow` and `Modpath7`) calls the UPW file to get `laytyp` and in my case seems to be functioning appropriately.

**Comment by TroelsNV** [comment] 2019-10-28 20:15
@jlarsen-usgs , thanks for looking at this. I have made a small test model that produces the error.
 
[MF_nwt_MP7_test_ss.zip](https://github.com/modflowpy/flopy/files/3780483/MF_nwt_MP7_test_ss.zip)

**Comment by jlarsen-usgs** [comment] 2019-10-28 21:00
@TroelsNV 

I've looked into the issue and it has been fixed with PR #601 on the develop branch. You can update to the most recent development version of flopy (3.2.13) by using

`pip install https://github.com/modflowpy/flopy/zipball/develop --upgrade`

**Closed** 2019-10-28 21:01 UTC
