### ISSUE TITLE
stress period packages like wel and ghb having issues with number of cells

### ISSUE THREAD

**Issue by rosskush** [modflowpy/flopy#312] opened 2018-03-29 15:15 UTC
Hey ya'll, 

So I have been dealing with an interesting issue lately. So when I am building a ghb package with stress period data, the sometimes the modflow throws an error that gives me 

FILE UNIT   23 : ERROR CONVERTING "#" TO AN INTEGER IN LINE:
         -1         0 # stress period 2  

I can look in the ghb (or wel) file and see based on the line numbers that there are more stress period data than the there actually is in the file.

for example this shows that there are 3552 ghbs in the stress perioed 
![image](https://user-images.githubusercontent.com/30669053/38096320-32ca8f28-3338-11e8-88ac-a32565525c12.png)

but when I scroll down I can see that there are less ghbs than 3552 in stress period 1.

![image](https://user-images.githubusercontent.com/30669053/38096413-66e2166e-3338-11e8-90a7-134d26e58ce3.png)

The weird thing is, and I cannot explain why, but sometimes it does work, then I rerun the script and then it does not work.

From investigating it, I think the 3552 number is correct and that not all the ghbs are are being written. 

This issue has happened to me with the wel package too.

 here is a link to a simplified version of my script if it helps,
https://github.com/rosskush/python_stuff/blob/master/python_stuff/S00_create_asr_box.py

**Comment by jtwhite79** [comment] 2018-03-29 20:11
Only kidding , Kush.  Its gonna be hard to find this issue if it only happens once and while.  If you can get it to happen consistently...

**Comment by rosskush** [comment] 2019-02-27 21:01
Unfortunately, even after deleting all the previous stress period files from the directory, I am still getting these issues where stress period data is not writing out to the wel (and other spd).

![image](https://user-images.githubusercontent.com/30669053/53522461-0b48a780-3aa0-11e9-92e2-9dee8d25da62.png)

for example, there should be 1 well in each stress period, and flopy is writing that, but it just sometimes does not write the well (lay row col flux) thus giving my model runs some errors. 

So I am reopening this issue.

**Comment by jtwhite79** [comment] 2019-02-27 22:01
Have you been able to force this to happen consistently? If so, do you have a minimum working example you can share?

**Comment by langevin-usgs** [comment] 2019-02-27 22:15
Could this be one of those python pointer errors biting you while you are creating the stress period data?  So that while you are creating the stress period dictionary you are somehow clobbering on previous stress period information?  If you create each stress period with a numpy recarray so that you are definitely allocating new memory for each period, would that help?  Just a guess here.

**Comment by rosskush** [comment] 2019-02-28 14:26
Jay, the same example I point to above does not work for me 100% of the time, but I am not able to reproduce it every time and especially on the same stress periods. 

Typically I write my stress period dictionaries where each stress period should not rely on any previous stresses and are defined by themselves, but I will try it using rec arrays rather than a dictionary and get back to you.

**Comment by jbellino-usgs** [comment] 2019-02-28 14:37
It's odd that `mxact` is correct (or different) than the actual maximum number of active boundary cells since that attribute should be coming directly from the recarrays you're passing into the GHB or WEL package class. I've taken to using the `write_file()` method to write each package after creation to ensure there are no chances for the spd objects to get changed (I notice you're using the same object called `spd` for multiple things and then writing all files at once at the end with `write_input()`).

I like to use Pandas DataFrames to build my stress period data—it's easier for me to manipulate, examine, plot, etc. Then I pass the data into whatever package using the `.to_records()` method:

```
ghb = pd.DataFrame(some_data, some_columns)

formats = OrderedDict([('lay', '{:>10d}'.format),
                       ('row', '{:>10d}'.format),
                       ('col', '{:>10d}'.format),
                       ('h', '{:>.2F}'.format),
                       ('cond', '{:>15.6E}'.format),
                       ('remark', '{:>50}'.format)])

ghb_spd = {0: ghb[list(formats.keys())].to_records(index=False)}

ghb = fpm.ModflowGhb(mf,
                     stress_period_data=ghb_spd,
                     ipakcb=53,
                     options=['NOPRINT'],
                     filenames=os.path.join('..', 'externalfiles', 'fas.ghb'),
                     dtype=ghb_spd[0].dtype)

ghb.write_file()
```

**Comment by langevin-usgs** [comment] 2019-04-06 21:03
Since this issue seems hard to reproduce, I'm going to close it.  If it resurfaces and there is something to fix, then please reopen.

**Closed by langevin-usgs** 2019-04-06 21:03 UTC

**Comment by rosskush** [comment] 2019-04-09 00:35
Thanks for looking into it. I have been giving the recarrays a try and I have not had issues since.
