### ISSUE TITLE
well package export, prevents stress period data from writing

### ISSUE THREAD

**Issue by khayley** [modflowpy/flopy#1217] opened 2021-08-31 07:39 UTC
Hi all, 
I have just been debugging a script to find out why wells were not active in a mf6 model I have been working on.
I tracked it down to a command used to export the well package to a shapefile for visualization in GIS.
“welPackage.export('model_wel.shp')” 
If I include this command in my script prior to writing the package to file then the resulting well file has no stress period data, if I comment that command out then the well package seems to write fine.
I get the same behaviour with both 3.3.4 and 3.3.5 flopy versions.
I have attached an example script with the export comand on line 130
[Build_model_simple_well_test.zip](https://github.com/modflowpy/flopy/files/7082069/Build_model_simple_well_test.zip)

Its beyond my understanding of the background package scripts to figure out why this might be happening, but just thought I would pass the observation along
Thanks
Kevin

**Comment by spaulins-usgs** [comment] 2022-01-11 23:17
@khayley, I am not able to reproduce this problem.  When I run your script as is with the export line included, the well file includes stress period data ("OPEN/CLOSE  'gwf-well_test.wel_stress_period_data_1.txt'").  I am running your script with the latest version of flopy on the develop branch.  Since this issue is over four months old it is possible that something changed in flopy that has now fixed the issue.  Please try the latest version of flopy on the develop branch.

**Comment by jdhughes-usgs** [comment] 2022-07-19 18:19
@khayley Closing for now. Reopen if the issue is not resolved.

**Closed by jdhughes-usgs** 2022-07-19 18:19 UTC
