### ISSUE TITLE
bug in make filenames with paths system agnostic mfreadnam.py 

### ISSUE THREAD

**Issue by ougx** [modflowpy/flopy#682] opened 2019-10-18 00:29 UTC
The code from Line 162 in `mfreadnam.py` will create error for absolute file path in Windows as `os.path.join` will left out the separator after the drive letter. See the discussion here: https://stackoverflow.com/questions/2422798/python-os-path-join-on-windows 

The original code:
```py 
       # need make filenames with paths system agnostic
        if '/' in fpath:
            raw = fpath.split('/')
        elif '\\' in fpath:
            raw = fpath.split('\\')
        else:
            raw = [fpath]
        fpath = os.path.join(*raw)
```

It can be fixed as follows:
```py 
       # need make filenames with paths system agnostic
        fpath = fpath.replace('\\', os.sep).replace('/', os.sep)
```

**Comment by langevin-usgs** [comment] 2019-10-18 00:48
Can you submit this as a pull request?  That would be helpful.

**Comment by langevin-usgs** [comment] 2019-10-18 01:27
I see there is similar code here:

https://github.com/modflowpy/flopy/blob/ff43c7ce6a3c1d7a446ed9e9bdb6097b932c3f06/flopy/pakbase.py#L836-L846

and probably elsewhere.

Let's keep this PR open, do a double-check on this proposed issue and fix (I didn't see your same syntax in the stackoverflow issue that you cite), and perhaps do a more comprehensive change throughout the code wherever separators are replaced.

**Comment by jdhughes-usgs** [comment] 2020-06-09 16:34
@langevin-usgs do you know where we are with this one?

**Comment by jdhughes-usgs** [comment] 2020-06-09 16:45
duplicate of #593

**Comment by jdhughes-usgs** [comment] 2021-08-16 14:33
Closing this issue.

**Closed by jdhughes-usgs** 2021-08-16 14:33 UTC
