### ISSUE TITLE
Improper node identification in MNW2

### ISSUE THREAD

**Issue by samzipper** [modflowpy/flopy#324] opened 2018-04-20 20:35 UTC
I am following along with the simple MNW2 example from [this iPython notebook](https://github.com/modflowpy/flopy/blob/develop/examples/Notebooks/flopy3_mnw2package_example.ipynb). (Thanks for the notebooks, BTW, they're super useful!). It lays out the following steps to create two wells, one of which spans two layers:

```
import pandas as pd
import flopy

# set up basic model
m = flopy.modflow.Modflow('mnw2example', model_ws='.')
dis = flopy.modflow.ModflowDis(nrow=5, ncol=5, nlay=3, nper=3, top=10, botm=0, model=m)

## build MNW2 package
# node data: example from iPython notebook
node_data = pd.DataFrame(
    [[1, 1, 9.5, 7.1, 'well1', 'skin', -1, 0, 0, 0, 1., 2., 5., 6.2],
     [1, 1, 7.1, 5.1, 'well1', 'skin', -1, 0, 0, 0, 1., 2., 5., 6.2],
     [3, 3, 9.1, 3.7, 'well2', 'skin', -1, 0, 0, 0, 1., 2., 5., 4.1]],
    columns=['i', 'j', 'ztop', 'zbotm', 'wellid', 'losstype', 'pumploc', 
    'qlimit', 'ppflag', 'pumpcap', 'rw', 'rskin', 'kskin', 'zpump'])
node_data = node_data.to_records()

# stress period information
stress_period_data = pd.DataFrame(
                         [[0, 'well1', 0],
                          [1, 'well1', 100.0],
                          [0, 'well2', 0],
                          [1, 'well2', 1000.]], 
        columns=['per', 'wellid', 'qdes'])
pers = stress_period_data.groupby('per')
stress_period_data = {i: pers.get_group(i).to_records() for i in [0, 1]}

# make package object
mnw2 = flopy.modflow.ModflowMnw2(model=m, mnwmax=2,
                 node_data=node_data, 
                 stress_period_data=stress_period_data, 
                 itmp=[2, 2, -1], # reuse second per pumping for last stress period
                 )
```

When I inspect the output of this well, it does indeed create 3 nodes:
```
In[127]: mnw2.nodtot

Out[127]: 3
```
However, both of the nodes for well1 appear to be in the same layer (k=0):

```
In[128]: pd.DataFrame(mnw2.node_data)

Out[128]: 
   k  i  j  ztop  zbotm wellid losstype  pumploc  qlimit  ppflag ...   hlim  \
0  0  1  1   7.1    5.1  well1     skin       -1       0       0 ...    0.0   
1  0  1  1   9.5    7.1  well1     skin       -1       0       0 ...    0.0   
2  0  3  3   9.1    3.7  well2     skin       -1       0       0 ...    0.0 
```

Furthermore, it should be possible to create well1 by providing a `ztop` and `zbotm` which span multiple layers, e.g.:
```
# combining the two 'well1' lines from previous example into one
node_data = pd.DataFrame(
    [[1, 1, 9.5, 5.1, 'well1', 'skin', -1, 0, 0, 0, 1., 2., 5., 6.2],
     [3, 3, 9.1, 3.7, 'well2', 'skin', -1, 0, 0, 0, 1., 2., 5., 4.1]],
    columns=['i', 'j', 'ztop', 'zbotm', 'wellid', 'losstype', 'pumploc', 
    'qlimit', 'ppflag', 'pumpcap', 'rw', 'rskin', 'kskin', 'zpump'])
node_data = node_data.to_records()

# make object
mnw2 = flopy.modflow.ModflowMnw2(model=m, mnwmax=2,
                 node_data=node_data, 
                 stress_period_data=stress_period_data, 
                 itmp=[2, 2, -1], # reuse second per pumping for last stress period
                 )
```

However, now we only get two nodes created (one per well):
```
In[134]: pd.DataFrame(mnw2.node_data)
Out[134]: 
   k  i  j  ztop  zbotm wellid losstype  pumploc  qlimit  ppflag ...   hlim  \
0  0  1  1   9.5    5.1  well1     skin       -1       0       0 ...    0.0   
1  0  3  3   9.1    3.7  well2     skin       -1       0       0 ...    0.0   
```
I am no Python expert but I poked around the [mfmnw2.py](https://github.com/modflowpy/flopy/blob/develop/flopy/modflow/mfmnw2.py) file and have a hunch of what's going on.

It looks like when `node_data` is provided as input, `nnodes` is set by calling the `get_nnodes` function (line 455):
` if node_data is not None:
    nnodes = Mnw.get_nnodes(node_data)`

The `get_nnodes` function sets `nnodes` equal to -1 if `ztop` or `zbotm` are defined (line 504):
```
    def get_nnodes(node_data):
        nnodes = len(node_data)
        # check if ztop and zbotm were entered,
        # flip nnodes for format 2
        if np.sum(node_data.ztop - node_data.zbotm) > 0:
            nnodes *= -1
        return nnodes
```

Then, starting on line 1397, dataset 2d is created by looping over the absolute value of `nnodes` (which will always be 1 if `ztop` and `zbotm` are defined:
```
    # dataset 2d
    pp = 1  # partial penetration flag
    for i in range(np.abs(nnodes)):
        line = line_parse(next(f))
        if nnodes > 0:
            d2d['k'].append(pop_item(line, int) - 1)
            d2d['i'].append(pop_item(line, int) - 1)
            d2d['j'].append(pop_item(line, int) - 1)
        elif nnodes < 0:
            d2d['ztop'].append(pop_item(line, float))
            d2d['zbotm'].append(pop_item(line, float))
            d2d['i'].append(pop_item(line, int) - 1)
            d2d['j'].append(pop_item(line, int) - 1)
```
I could be totally wrong (I still don't really understand python namespaces, functions, or much else TBH). Has anyone been able to create an MNW2 well that successfully spans multiple layers by defining the top and bottom elevations?

**Comment by dbrakenhoff** [comment] 2018-06-06 08:44
Seems to me like MODFLOW is working fine. MODFLOW assigns wells to nodes based on well elevations. Not sure if it's intentional, but Flopy doesn't seem to do that. 

This is from the LIST file with MNWPRNT=2 when I run a small model with a slightly altered version of the wells from the example notebook. It shows that well2 is assigned to layers 1 and 2 based on Ztop and Zbotm, which is what I would expect.

```
WELLID             NNODES    LOSSTYPE PUMPLOC  Qlimit  PPFLAG PUMPCAP
 WELL2                  -1      SKIN        -1       0       0       0
 
 NNODES < 0: well defined using open intervals as described below
 Interval      Ztop       Zbotm      Row  Col      Rw       Rskin      Kskin 
    1        9.1000      3.7000        4    4   0.1000      2.000      5.000    
 
 The following nodes were assigned to this well based on above open interval information
 Node  Lay  Row  Col 
    1    1    4    4
    2    2    4    4
 ZPUMP (Elev.) =     4.100, CONVERTED TO NODE LOCATION: LAY =   2, ROW =   4, COL =   4
```

So not sure, if this is an issue in flopy that still needs to be fixed, but figured I'd share that MODFLOW seems to do fine with wells spanning multiple layers.

**Comment by aleaf** [comment] 2020-06-22 20:04
Hey @samzipper, sorry for never answering this. I looked at your example code and as far as I can tell, flopy seems to be working as intended. I think the confusion lies in the idiosyncrasies of MNW2 input. Nodes for a well can be defined by layer, row, column, or by open intervals (ztop and zbotm variables). From the [MODFLOW Online Guide for MNW2 Dataset 2b](https://water.usgs.gov/ogw/modflow-nwt/MODFLOW-NWT-Guide/):

> _If an interval partially or fully intersects a model layer, then a node will be defined in that cell. If more than one open interval intersects a particular layer, then a length-weighted average of the cell-to-well conductances will be used to define the well-node characteristics; for purposes of calculating effects of partial penetration, the cumulative length of well screens will be assumed to be centered vertically within the thickness of the cell._

With the open interval (ztop, zbotm) option, multiple nodes representing an interval that spans multiple layers are defined internally by the MNW2 package, but the input file only has 1 entry with ztop, zbotm. Hence why the `node_data` table only has one entry for well2 above, even though it spans two layers (the layer bottoms at that location are 10, 5, and 0).

For posterity, here is the resulting MNW2 input file:
```python
mnw2.write_file()
with open(mnw2.file_name[0]) as src:
    print(src.read())
```
```
# MNW2 package for  MODFLOW-2005, generated by Flopy.
2 0 0
well1 -2
            skin -1 0 0 0
               1.0000000E+00    2.0000000E+00    5.0000000E+00
               9.5000000E+00    7.0999999E+00 2 2
               7.0999999E+00    5.0999999E+00 2 2
               6.1999998E+00
well2 -1
            skin -1 0 0 0
               1.0000000E+00    2.0000000E+00    5.0000000E+00
               9.1000004E+00    3.7000000E+00 4 4
               4.0999999E+00
2  Stress Period 1
well1    0.0000000E+00
well2    0.0000000E+00
2  Stress Period 2
well1    1.0000000E+02
well2    1.0000000E+03
-1  Stress Period 3
```
Hope this makes sense.

**Comment by jdhughes-usgs** [comment] 2020-06-23 18:10
@aleaf-usgs do you happen to know if this is still an issue? If it is not an issue would you close?

**Closed** 2020-06-23 20:00 UTC
