### ISSUE TITLE
Inconsistency in get_lrc()

### ISSUE THREAD

**Issue by robinthibaut** [modflowpy/flopy#806] opened 2020-02-06 14:50 UTC
**Summary:**
Given a well with _layer, row, column, node_:
`[k, i, j, n]`
`get_lrc(n)` returns `[(k+1, i+1, j]` instead of the expected `[(k, i, j)]`.

**My issue:**
Given a Modflow model generated by:
 `modflow_model = flopy.modflow.Modflow(args)`:

`modflow_model.wel.stress_period_data.df.values`
Returns for example, for one pumping well and one stress period:
`array([[0, 56, 137, 10945, -1000]])`
That is:
`array([[layer, row, column, node number, pumping rate]])`.

Well node = 10945. If I perform the following:
`modflow_model.dis.get_lrc(10945)`

I would expect to obtain:
`[(0, 56, 137)]`

However, I obtain the following:
`[(1, 57, 137)]`

**Flopy version:**
3.3.0

**Code sample**
Find attached a 55-lines code sample. The issue starts at line 42.

[bug.zip](https://github.com/modflowpy/flopy/files/4165605/bug.zip)

**Comment by sharon92** [comment] 2020-03-16 14:26
from the flopy documentation:

```

get_lrc(self, nodes)
Get layer, row, column from a list of MODFLOW node numbers.

Returns
vlist of tuples containing the layer (k), row (i),
and column (j) for each node in the input list
```

as you can see the input is indeed Modflow based node numbers and these are not 0 based.
so the output is correct.

and if you are expecting a 0 based output, you will need to substract 1 from the tuples,
you should expect (0,56,136)

What however IS inconsistent is the get_node() function. Here the expected input is Modflow layer,row,column but the output is 0 based node.

**Comment by jlarsen-usgs** [comment] 2020-03-16 16:09
@robinthibaut and @sharon92 

I'll take a look at this issue.

**Comment by robinthibaut** [comment] 2020-04-10 13:20
@sharon92 
The column remains inconsistent. As stated in my issue, from (k, i, j), you obtain (k+1, i+1,  **j**). If it was truly "1-based" then you would expect (k+1, i+1, **j+1**).

@jlarsen-usgs 
Thanks !

Kind regards,

Robin

**Comment by jdlarsen-UA** [comment] 2020-04-10 15:33
@sharon92, @robinthibaut, @langevin-usgs .

I looked into it this morning and the issue is that `get_lrc()` expects a 1 based node number and returns a one based (layer, row, column) and that the `get_node()` method expects a zero based (layer, row, column) and returns a zero based node number.  It makes more sense to me to have both methods expect and return zero based values for consistency.

**Comment by jlarsen-usgs** [comment] 2020-04-10 21:32
@sharon92, @robinthibaut 

Closing this issue. I updated both methods to 1) be parameterized with zero based inputs, and 2) return zero based outputs.

**Closed by jlarsen-usgs** 2020-04-10 21:32 UTC

**Comment by langevin-usgs** [comment] 2021-02-04 20:34
This was revised again with #1049.  Should hopefully be fixed now.
