### ISSUE TITLE
Exception error when creating shapefiles with GRIDGEN

### ISSUE THREAD

**Issue by cbouman** [modflowpy/flopy#530] opened 2019-04-15 07:11 UTC
I was programming the tutorial on the GRIDGEN module (https://github.com/modflowpy/flopy/blob/develop/examples/Notebooks/flopy3_gridgen.ipynb), but I received an Exception Error at this line:

g.add_refinement_features(wells, 'point', 3, range(nlay))

Exception: Either the target filepath, or any of shp, shx, or dbf must be set to create a shapefile.

I already checked my filepaths and everything seems well-defined. What is happening here?

**Comment by langevin-usgs** [comment] 2019-04-15 11:43
You have not provided enough information for us to reproduce this problem.  The flopy3_gridgen notebook works fine for me and passes the tests on travis.  Do you have the gridgen executable in your path and on your system?  This is likely not a bug, so I'm closing this issue.

**Closed by langevin-usgs** 2019-04-15 11:43 UTC
