### ISSUE TITLE
MF6: obscure issue with remaking SFR after removing package

### ISSUE THREAD

**Issue by aleaf** [modflowpy/flopy#1111] opened 2021-05-12 20:24 UTC
This may not affect many users, but I came across this error when trying to remake an SFR package after removing it:
```python
import flopy
mf6 = flopy.mf6

sim = mf6.MFSimulation()
model = mf6.ModflowGwf(sim)
dis = mf6.ModflowGwfdis(model, length_units='FEET', nlay=1,
                                     nrow=2, ncol=2, delr=500.0,
                                     delc=500.0,
                                     top=100.0, botm=50.0,
                                     filename='{}.dis'.format(model_name))

packagedata=[(0, (0, 0, 1), 110, 90.0, 0.0001, 100, 1, 1, 0.37, 1, 1.0, 0)]
sfr = mf6.ModflowGwfsfr(model, packagedata=packagedata)
model.remove_package('SFR_0')
sfr = mf6.ModflowGwfsfr(model, packagedata=packagedata)
```
```python
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
~/opt/anaconda3/envs/gis/lib/python3.8/site-packages/numpy/core/records.py in fromrecords(recList, dtype, shape, formats, names, titles, aligned, byteorder)
    743     try:
--> 744         retval = sb.array(recList, dtype=descr)
    745     except (TypeError, ValueError):

ValueError: could not assign tuple of length 3 to structure with 2 fields.

During handling of the above exception, another exception occurred:

ValueError                                Traceback (most recent call last)
~/Documents/GitHub/flopy/flopy/mf6/data/mfdatalist.py in append_list_as_record(self, record)
    569             # store
--> 570             self._get_storage_obj().append_data([tuple_record])
    571         except Exception as ex:

~/Documents/GitHub/flopy/flopy/mf6/data/mfdatastorage.py in append_data(self, data)
    859                             internal_data,
--> 860                             np.rec.array(data, self._recarray_type_list),
    861                         )

~/opt/anaconda3/envs/gis/lib/python3.8/site-packages/numpy/core/records.py in array(obj, dtype, shape, offset, strides, formats, names, titles, aligned, byteorder, copy)
    986         if isinstance(obj[0], (tuple, list)):
--> 987             return fromrecords(obj, dtype=dtype, shape=shape, **kwds)
    988         else:

~/opt/anaconda3/envs/gis/lib/python3.8/site-packages/numpy/core/records.py in fromrecords(recList, dtype, shape, formats, names, titles, aligned, byteorder)
    755         for k in range(_array.size):
--> 756             _array[k] = tuple(recList[k])
    757         # list of lists instead of list of tuples ?

ValueError: could not assign tuple of length 3 to structure with 2 fields.

During handling of the above exception, another exception occurred:

MFDataException                           Traceback (most recent call last)
<ipython-input-26-f43b10c908aa> in <module>
----> 1 sfr = mf6.ModflowGwfsfr(model, packagedata=packagedata)

~/Documents/GitHub/flopy/flopy/mf6/modflow/mfgwfsfr.py in __init__(self, model, loading_package, auxiliary, boundnames, print_input, print_stage, print_flows, save_flows, stage_filerecord, budget_filerecord, package_convergence_filerecord, timeseries, observations, mover, maximum_picard_iterations, maximum_iterations, maximum_depth_change, unit_conversion, nreaches, packagedata, connectiondata, diversions, perioddata, filename, pname, parent_file)
   1106         parent_file=None,
   1107     ):
-> 1108         super().__init__(
   1109             model, "sfr", filename, pname, loading_package, parent_file
   1110         )

~/Documents/GitHub/flopy/flopy/mf6/mfpackage.py in __init__(self, model_or_sim, package_type, filename, pname, loading_package, parent_file)
   1535             self._filename = MFFileMgmt.string_to_file_path(filename)
   1536 
-> 1537         self.path, self.structure = model_or_sim.register_package(
   1538             self, not loading_package, pname is None, filename is None
   1539         )

~/Documents/GitHub/flopy/flopy/mf6/mfmodel.py in register_package(self, package, add_to_package_list, set_package_name, set_package_filename)
   1242                 # Model Assumption - assuming all name files have a package
   1243                 # recarray
-> 1244                 self.name_file.packages.update_record(
   1245                     [
   1246                         "{}6".format(pkg_type),

~/Documents/GitHub/flopy/flopy/mf6/data/mfdatalist.py in update_record(self, record, key_index)
    587 
    588     def update_record(self, record, key_index):
--> 589         self.append_list_as_record(record)
    590 
    591     def search_data(self, search_term, col=None):

~/Documents/GitHub/flopy/flopy/mf6/data/mfdatalist.py in append_list_as_record(self, record)
    571         except Exception as ex:
    572             type_, value_, traceback_ = sys.exc_info()
--> 573             raise MFDataException(
    574                 self.structure.get_model(),
    575                 self.structure.get_package(),

MFDataException: An error occurred in data element "packages" model "gwf6" package "nam". The error occurred while appending data in the "append_list_as_record" method.
```

**Comment by spaulins-usgs** [comment] 2021-11-05 14:10
@aleaf There have been a number of fixes they may have fixed this issue since it was created.  I just tested the example code with the latest flopy on the develop branch and it now works.  Going to close this issue unless you can still reproduce it.

**Comment by aleaf** [comment] 2021-11-05 14:29
great, thanks @spaulins

**Closed** 2021-11-30 16:25 UTC
